# Generated by Django 2.2.1 on 2019-05-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0002_article_author_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='linkedinid',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='researchid',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='scopusid',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
