# Generated by Django 2.2.1 on 2019-06-19 20:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confTitle', models.CharField(max_length=100)),
                ('confFamily', models.CharField(blank=True, max_length=100, null=True)),
                ('location_country', models.CharField(blank=True, max_length=100, null=True)),
                ('location_city', models.CharField(blank=True, max_length=100, null=True)),
                ('dates_start', models.DateField(blank=True, null=True)),
                ('dates_end', models.DateField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('contacts_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contacts_phoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('acceptance_rate', models.FloatField(blank=True, null=True)),
                ('impact_factor', models.FloatField(blank=True, null=True)),
                ('sponsors', models.TextField(blank=True, null=True)),
                ('paperDeadline', models.DateField(blank=True, null=True)),
                ('pageNumber_min', models.IntegerField(blank=True, null=True)),
                ('pageNumber_max', models.IntegerField(blank=True, null=True)),
                ('pageNumber_ave', models.FloatField(blank=True, null=True)),
                ('field', models.TextField(blank=True, null=True)),
                ('isRegistered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creation', models.DateField(default=datetime.date.today)),
                ('data_last_update', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Conference')),
            ],
        ),
        migrations.CreateModel(
            name='UserConferenceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submissions', models.ManyToManyField(through='conference.Submission', to='conference.Conference')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.UserConferenceInfo'),
        ),
    ]
