# Generated by Django 2.2.2 on 2019-06-26 16:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('abstract', models.TextField()),
                ('keywords', models.TextField()),
                ('paper', models.TextField()),
                ('subject_areas', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confTitle', models.CharField(max_length=100)),
                ('confFamily', models.CharField(blank=True, max_length=100, null=True)),
                ('location_country', models.CharField(blank=True, max_length=100, null=True)),
                ('location_city', models.CharField(blank=True, max_length=100, null=True)),
                ('coords_lat', models.FloatField(blank=True, null=True)),
                ('coords_lng', models.FloatField(blank=True, null=True)),
                ('dates_start', models.DateField(blank=True, null=True)),
                ('dates_end', models.DateField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('contacts_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contacts_phoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('sponsors', models.TextField(blank=True, null=True)),
                ('paperDeadline', models.DateField(blank=True, null=True)),
                ('additionalDeadlines_submission', models.DateField(blank=True, null=True)),
                ('additionalDeadlines_notification', models.DateField(blank=True, null=True)),
                ('additionalDeadlines_conference', models.DateField(blank=True, null=True)),
                ('pageNumber_min', models.IntegerField(blank=True, null=True)),
                ('pageNumber_max', models.IntegerField(blank=True, null=True)),
                ('pageNumber_ave', models.FloatField(blank=True, null=True)),
                ('field', models.TextField(blank=True, null=True)),
                ('gen_field', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creation', models.DateField(default=datetime.date.today)),
                ('data_last_update', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Article')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Conference')),
            ],
        ),
        migrations.CreateModel(
            name='UserConferenceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestions', models.CharField(max_length=200, null=True)),
                ('submissions', models.ManyToManyField(through='conference.Submission', to='conference.Conference')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.UserConferenceInfo'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
