# Generated by Django 2.2.1 on 2019-06-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconferenceinfo',
            name='suggestions',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
